[package]
name = "buckets"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fasthash = { version = "0.4.0" }
rayon = { version = "1.5.1" }

[dev-dependencies]
rand = { version = "0.8.4" }